// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3MEGNMBUkh8roOENNxjWC-ZAt3Lnfqk',
    appId: '1:185917106202:android:57194c45a537767d03c9a3',
    messagingSenderId: '185917106202',
    projectId: 'webproj1-a',
    databaseURL: 'https://webproj1-a.firebaseio.com',
    storageBucket: 'webproj1-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPOtDy4jCmhx8GX7amVkVN87qhn843s1g',
    appId: '1:185917106202:ios:959002cd30c6bc2403c9a3',
    messagingSenderId: '185917106202',
    projectId: 'webproj1-a',
    databaseURL: 'https://webproj1-a.firebaseio.com',
    storageBucket: 'webproj1-a.appspot.com',
    androidClientId:
        '185917106202-kde48k9vvphsnin4askjtcrcoikh3ab7.apps.googleusercontent.com',
    iosClientId:
        '185917106202-khq72q3tqv3vgc0vtl6ejm56qn88f5is.apps.googleusercontent.com',
    iosBundleId: 'com.deadliners.sms',
  );
}
