// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPx6nt_ld8YpJXVo0NkwDb6pDalJJwq4',
    appId: '1:292234043645:android:4f3a59e31ceddac8c05e94',
    messagingSenderId: '292234043645',
    projectId: 'supplychain-a03de',
    storageBucket: 'supplychain-a03de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSUNpGhpSFZ_-sy8ISCYQdL4DPbzSUyo',
    appId: '1:292234043645:ios:eda764f1980d8209c05e94',
    messagingSenderId: '292234043645',
    projectId: 'supplychain-a03de',
    storageBucket: 'supplychain-a03de.appspot.com',
    iosClientId:
        '292234043645-8n7gtm3daqnq7e0kscpd25qbhfasbdmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );
}
